"""Broker Protocol the rest of the system depends on. The domain layer
must not import from broker.oanda directly; only this Protocol."""

from __future__ import annotations

from collections.abc import Iterator
from decimal import Decimal
from typing import Literal, Protocol

from forex_bot.domain.account import AccountDetails, AccountSnapshot
from forex_bot.domain.candles import Candle, CandleRequest
from forex_bot.domain.instruments import Instrument
from forex_bot.domain.market import Quote
from forex_bot.domain.orders import BrokerOrder, BrokerOrderResult, OrderPlan
from forex_bot.domain.positions import Position, Trade
from forex_bot.domain.transactions import Heartbeat, Transaction

BrokerEnvironment = Literal["practice", "live"]


class Broker(Protocol):
    environment: BrokerEnvironment
    account_id: str

    def get_account_summary(self) -> AccountSnapshot: ...
    def get_account_details(self) -> AccountDetails: ...
    def list_instruments(self) -> list[Instrument]: ...
    def get_candles(self, request: CandleRequest) -> list[Candle]: ...
    def get_prices(self, instruments: list[str]) -> list[Quote]: ...
    def stream_prices(self, instruments: list[str]) -> Iterator[Quote | Heartbeat]: ...
    def list_open_orders(self) -> list[BrokerOrder]: ...
    def list_open_trades(self) -> list[Trade]: ...
    def list_positions(self) -> list[Position]: ...
    def submit_order(self, plan: OrderPlan) -> BrokerOrderResult: ...
    def close_trade(
        self, trade_id: str, units: Decimal | None = None
    ) -> BrokerOrderResult: ...
    def get_transactions_since(self, last_transaction_id: str) -> list[Transaction]: ...
    def stream_transactions(self) -> Iterator[Transaction | Heartbeat]: ...
